
local words = {
	['print'] = 'builtin',
	['warn'] = 'builtin',
	['Vector3'] = 'builtin',
	['Vector2'] = 'builtin',
  ['UDim'] = 'builtin',
  ['UDim2'] = 'builtin',
	['error'] = 'builtin',
	['Instance'] = 'builtin',
	['game'] = 'builtin',
	['script'] = 'builtin',
	['workspace'] = 'builtin',
  ['assert'] = 'builtin',
  ['task'] = 'builtin',
  ['wait'] = 'builtin',
  ['pairs'] = 'builtin',
  ['ipairs'] = 'builtin',
	['next'] = 'builtin',
  ['loadstring'] = 'builtin',
  ['Enum'] = 'builtin',
  ['TweenInfo'] = 'builtin',
	['while'] = 'keyword',
	['true'] = 'keyword',
	['false'] = 'keyword',
	['then'] = 'keyword',
	['do'] = 'keyword',
	['if'] = 'keyword',
  ['end'] = 'keyword',
  ['elseif'] = 'keyword',
  ['else'] = 'keyword',
  ['return'] = 'keyword',
  ['local'] = 'keyword',
  ["getgenv()"] = "keyword",
  ["getrenv()"] = "keyword"
}

return words
